import sanitizeHtml from 'sanitize-html';
import { Post } from '../schemas/post.js';

/**
 * Static HTML preview page for a carousel. Contains NO credentials, secrets or
 * internal debug data. In TEST mode this preview IS the system draft.
 */

function esc(text: string): string {
  return sanitizeHtml(text, { allowedTags: [], allowedAttributes: {} });
}

export interface PreviewInput {
  post: Post;
  slideUrls: string[];
  mode: 'TEST' | 'LIVE';
  label: 'DRAFT' | 'PUBLISHED';
  permalink?: string | null;
}

export function buildPreviewHtml(input: PreviewInput): string {
  const { post, slideUrls, mode, label, permalink } = input;
  const slides = slideUrls
    .map(
      (url, i) =>
        `<figure class="slide"><img src="${esc(url)}" alt="Slide ${i + 1}" width="1080" height="1350" loading="lazy"><figcaption>Slide ${i + 1} / ${slideUrls.length}</figcaption></figure>`,
    )
    .join('\n');
  const hashtags = post.hashtags.map((h) => (h.startsWith('#') ? h : `#${h}`)).join(' ');
  const permalinkHtml = permalink
    ? `<p class="permalink"><a href="${esc(permalink)}" target="_blank" rel="noopener">View on Instagram →</a></p>`
    : '';

  return `<!doctype html>
<html lang="${esc(post.slides[0]?.kicker ? 'en' : 'en')}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex">
<title>Carousel Preview — ${esc(post.idea).slice(0, 60)}</title>
<style>
  :root { color-scheme: light dark; --bg:#0f1117; --card:#191c24; --text:#e8eaf0; --muted:#9aa1b2; --accent:#3B6FE0; }
  * { box-sizing: border-box; }
  body { margin:0; font-family: -apple-system, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
    background: var(--bg); color: var(--text); line-height:1.5; }
  header { padding: 28px 24px; border-bottom:1px solid #2a2e3a; position: sticky; top:0; background: var(--bg); z-index:2; }
  .badge { display:inline-block; padding:6px 14px; border-radius:999px; font-weight:700; font-size:13px;
    letter-spacing:1px; text-transform:uppercase; }
  .badge.draft { background:#3a2f00; color:#ffd54a; }
  .badge.published { background:#0d3b1e; color:#5fe08a; }
  .mode { color: var(--muted); font-size:14px; margin-left:10px; }
  h1 { font-size: 26px; margin: 14px 0 6px; }
  .hook { color: var(--muted); font-size:16px; margin:0; }
  main { max-width: 960px; margin: 0 auto; padding: 24px; }
  .meta { display:flex; flex-wrap:wrap; gap:12px; margin: 16px 0 28px; font-size:14px; color:var(--muted); }
  .meta span { background: var(--card); padding:8px 14px; border-radius:10px; }
  .grid { display:grid; grid-template-columns: repeat(auto-fill, minmax(240px, 1fr)); gap:18px; }
  .slide { margin:0; background: var(--card); border-radius:14px; overflow:hidden; }
  .slide img { width:100%; height:auto; display:block; }
  figcaption { padding:10px 14px; font-size:13px; color:var(--muted); }
  .caption { white-space: pre-wrap; background: var(--card); padding:22px; border-radius:14px; margin-top:28px; font-size:15px; }
  .hashtags { color: var(--accent); margin-top:12px; font-size:15px; }
  .permalink a { color: var(--accent); font-weight:600; }
  footer { text-align:center; color:var(--muted); font-size:13px; padding:32px; }
</style>
</head>
<body>
<header>
  <span class="badge ${label.toLowerCase()}">${label}</span><span class="mode">Mode: ${esc(mode)}</span>
  <h1>${esc(post.idea)}</h1>
  <p class="hook">${esc(post.hook)}</p>
</header>
<main>
  <div class="meta">
    <span>Pillar: ${esc(post.content_pillar)}</span>
    <span>Template: ${esc(post.template)}</span>
    <span>Slides: ${slideUrls.length}</span>
    <span>Generated: ${esc(post.generated_at)}</span>
  </div>
  ${permalinkHtml}
  <div class="grid">
    ${slides}
  </div>
  <div class="caption">${esc(post.caption)}<div class="hashtags">${esc(hashtags)}</div></div>
</main>
<footer>Generated by insta-carousel-generator · ${esc(mode)} mode · not for public indexing</footer>
</body>
</html>`;
}
